title: bsauce's blog, pwning to make friends
email: fengqiuluo@outlook.com
author:
  picture: http://bsauce.github.io/assets/img/compressed/hugo.jpg #URL FORMAT
  name: bsauce
  location: Beijing - China
  description: "Look up at the stars, and stand on solid ground."  
description: only my simple vision of casper theme
baseurl: "/"
url: http://bsauce.github.io
twitter_username: none
github_username:  bsauce
github_url: https://github.com/bsauce

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
